home:
    type:     annotation
    resource: "@ATSScheduleBundle/Controller/DefaultController.php"

scheduler_subjects:
    type:     rest
    resource: "@ATSScheduleBundle/Controller/SubjectController.php"

scheduler_courses:
    type:     rest
    parent:   scheduler_subjects
    resource: "@ATSScheduleBundle/Controller/CourseController.php"

ats_scheduler:
    type:     rest
    resource: "@ATSScheduleBundle/Controller/"
