services:
    ats_schedule.book_parser:
        class: ATS\Bundle\ScheduleBundle\Util\Parser\BookParser
        arguments:
            - "@doctrine"
        calls:
            - [setRootDir, ["%kernel.root_dir%"]]
    
    schedule.import_helper:
        class:  ATS\Bundle\ScheduleBundle\Util\Helper\ImportDriverHelper
        arguments:
            - "@doctrine"
            - "%num_years%"
    
    schedule.book_import:
        parent: schedule.abstract_import
        class:  ATS\Bundle\ScheduleBundle\Util\Parser\BookImportDriver
    
    schedule.ods_import:
        parent: schedule.abstract_import
        class:  ATS\Bundle\ScheduleBundle\Util\Parser\OdsImportDriver
    
    schedule.abstract_import:
        abstract: true
        arguments:
            - "@doctrine"
            - "@schedule.import_helper"
        calls:
            - [init]
    
    schedule.cache.database:
        class: SQLite3
        arguments:
            - "%kernel.root_dir%/../var/cache/%kernel.environment%/cache.sqlite"
    
    schedule.cache.provider:
        class: Doctrine\Common\Cache\SQLite3Cache
        arguments:
            - "@schedule.cache.database"
            - "cache"
    
    schedule.cache.adapter:
        class: Symfony\Component\Cache\Adapter\DoctrineAdapter
        arguments:
            - "@schedule.cache.provider"
            - "classplan"
            - "86400"