imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                logging:   false
                profiling: false
                driver:    pdo_mysql
                host:      "%oudev_db_host%"
                port:      "%oudev_db_port%"
                dbname:    "%oudev_db_name%"
                user:      "%oudev_db_user%"
                password:  "%oudev_db_password%"
                charset:   UTF8
            ods:
                logging:   false
                profiling: false
                driver:    pdo_mysql
                host:      "%ods_db_host%"
                port:      "%ods_db_port%"
                dbname:    "%ods_db_name%"
                user:      "%ods_db_user%"
                password:  "%ods_db_password%"
                charset:   UTF8
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    ATSScheduleBundle: ~
            #ods:
                #connection: ods